#!/usr/bin/env python3
import browser_cookie3
import sys

def extract_patreon_cookies(browser_name='chrome'):
    print(f"Attempting to extract Patreon cookies from {browser_name}...")
    
    try:
        if browser_name == 'chrome':
            cookies = browser_cookie3.chrome()
        elif browser_name == 'firefox':
            cookies = browser_cookie3.firefox()
        elif browser_name == 'safari':
            cookies = browser_cookie3.safari()
        else:
            print(f"Unsupported browser: {browser_name}")
            return False
        
        # Extract Patreon cookies
        patreon_cookies = []
        for cookie in cookies:
            if 'patreon.com' in cookie.domain:
                patreon_cookies.append(cookie)
        
        if not patreon_cookies:
            print("No Patreon cookies found. Please make sure you're logged in to Patreon in your browser.")
            return False
        
        print(f"Found {len(patreon_cookies)} Patreon cookies")
        
        # Write cookies in Netscape format for yt-dlp
        with open("patreon_cookies.txt", "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by extract_browser_cookies.py\n")
            
            for cookie in patreon_cookies:
                secure = "TRUE" if cookie.secure else "FALSE"
                http_only = "FALSE"  # Set to FALSE for compatibility
                expires = str(int(cookie.expires)) if cookie.expires else "0"
                domain = cookie.domain
                # Ensure domain starts with a dot for subdomains
                if not domain.startswith('.') and not domain.startswith('www'):
                    domain = domain
                path = cookie.path if cookie.path else "/"
                name = cookie.name
                value = cookie.value
                
                # Skip cookies with special characters in values that might break the format
                if '\t' in value or '\n' in value:
                    print(f"Skipping cookie {name} due to special characters")
                    continue
                
                f.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
        
        print("Cookies saved to patreon_cookies.txt")
        return True
        
    except Exception as e:
        print(f"Error extracting cookies: {e}")
        print("\nTroubleshooting tips:")
        print("1. Make sure you're logged in to Patreon in your browser")
        print("2. Close your browser completely before running this script")
        print("3. Try a different browser (chrome, firefox, safari)")
        return False

if __name__ == "__main__":
    browser = sys.argv[1] if len(sys.argv) > 1 else 'chrome'
    
    print(f"Extracting cookies from {browser}...")
    print("Note: You may need to close your browser for this to work properly.\n")
    
    if extract_patreon_cookies(browser):
        print("\nSuccess! You can now download Patreon videos with:")
        print('python3 -m yt_dlp --cookies patreon_cookies.txt "https://www.patreon.com/posts/137239514"')
        print('python3 -m yt_dlp --cookies patreon_cookies.txt "https://www.patreon.com/posts/secret-training-136705940"')
    else:
        print("\nFailed to extract cookies. Please try:")
        print("1. Log in to Patreon in your browser")
        print("2. Close the browser completely")
        print("3. Run this script again")
        print("\nOr try a different browser:")
        print("python3 extract_browser_cookies.py chrome")
        print("python3 extract_browser_cookies.py firefox")
        print("python3 extract_browser_cookies.py safari")