#!/usr/bin/env python3
import browser_cookie3
import json
import sys

def extract_patreon_cookies_json(browser_name='chrome'):
    print(f"Extracting Patreon cookies from {browser_name} to JSON format...")
    
    try:
        if browser_name == 'chrome':
            cookies = browser_cookie3.chrome()
        elif browser_name == 'firefox':
            cookies = browser_cookie3.firefox()
        elif browser_name == 'safari':
            cookies = browser_cookie3.safari()
        else:
            print(f"Unsupported browser: {browser_name}")
            return False
        
        # Extract Patreon cookies
        patreon_cookies = []
        for cookie in cookies:
            if 'patreon.com' in cookie.domain:
                cookie_dict = {
                    'name': cookie.name,
                    'value': cookie.value,
                    'domain': cookie.domain,
                    'path': cookie.path if cookie.path else '/',
                    'secure': cookie.secure,
                    'expires': int(cookie.expires) if cookie.expires else None
                }
                # Add session_id specifically if it exists
                if cookie.name == 'session_id':
                    print(f"Found session_id cookie: {cookie.value[:20]}...")
                patreon_cookies.append(cookie_dict)
        
        if not patreon_cookies:
            print("No Patreon cookies found. Please make sure you're logged in to Patreon in your browser.")
            return False
        
        print(f"Found {len(patreon_cookies)} Patreon cookies")
        
        # Save as JSON for yt-dlp
        with open("patreon_cookies.json", "w") as f:
            json.dump(patreon_cookies, f, indent=2)
        
        print("Cookies saved to patreon_cookies.json")
        
        # Also create a cleaned Netscape format file
        with open("patreon_cookies_clean.txt", "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by extract_cookies_json.py\n")
            
            for cookie in patreon_cookies:
                # Skip cookies with problematic values
                if cookie['name'] in ['g_state', '__cf_bm', '_cfuvid']:
                    print(f"Skipping problematic cookie: {cookie['name']}")
                    continue
                    
                secure = "TRUE" if cookie.get('secure', False) else "FALSE"
                expires = str(cookie.get('expires', 0))
                domain = cookie['domain']
                if domain == 'www.patreon.com':
                    domain = '.patreon.com'
                path = cookie.get('path', '/')
                name = cookie['name']
                value = cookie['value']
                
                f.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
        
        print("Clean cookies saved to patreon_cookies_clean.txt")
        return True
        
    except Exception as e:
        print(f"Error extracting cookies: {e}")
        return False

if __name__ == "__main__":
    browser = sys.argv[1] if len(sys.argv) > 1 else 'chrome'
    
    if extract_patreon_cookies_json(browser):
        print("\nSuccess! You can now use:")
        print('python3 -m yt_dlp --cookies patreon_cookies.json "URL"')
        print('or')
        print('python3 -m yt_dlp --cookies patreon_cookies_clean.txt "URL"')