#!/usr/bin/env python3
import asyncio
import json
import sys
from playwright.async_api import async_playwright
import getpass

async def login_to_patreon():
    print("Please enter your Patreon credentials:")
    email = input("Email: ")
    password = getpass.getpass("Password: ")
    
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()
        
        print("Navigating to Patreon login page...")
        await page.goto("https://www.patreon.com/login")
        
        print("Filling in login credentials...")
        await page.fill('input[name="email"]', email)
        await page.fill('input[name="password"]', password)
        
        print("Clicking login button...")
        await page.click('button[type="submit"]')
        
        print("Waiting for login to complete...")
        try:
            await page.wait_for_url("https://www.patreon.com/home", timeout=30000)
            print("Login successful!")
        except:
            print("Login might require additional verification. Please complete it manually in the browser.")
            input("Press Enter when you've completed the login...")
        
        print("Extracting cookies...")
        cookies = await context.cookies()
        
        # Convert cookies to Netscape format for yt-dlp
        with open("patreon_cookies.txt", "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by patreon_login.py\n")
            for cookie in cookies:
                secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                http_only = "TRUE" if cookie.get("httpOnly", False) else "FALSE"
                expires = str(int(cookie.get("expires", -1)))
                if expires == "-1":
                    expires = "0"
                domain = cookie["domain"]
                if not domain.startswith("."):
                    domain = "." + domain
                path = cookie.get("path", "/")
                name = cookie["name"]
                value = cookie["value"]
                
                f.write(f"{domain}\t{http_only}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
        
        print("Cookies saved to patreon_cookies.txt")
        
        # Also save as JSON for backup
        with open("patreon_cookies.json", "w") as f:
            json.dump(cookies, f, indent=2)
        print("Cookies also saved to patreon_cookies.json (backup)")
        
        await browser.close()
        print("\nLogin complete! You can now use yt-dlp with --cookies patreon_cookies.txt")

if __name__ == "__main__":
    asyncio.run(login_to_patreon())