#!/usr/bin/env python3
import asyncio
import json
import sys
import os
from playwright.async_api import async_playwright

async def login_to_patreon(email=None, password=None):
    if not email:
        email = os.environ.get('PATREON_EMAIL')
        if not email:
            print("Error: Please set PATREON_EMAIL environment variable or pass email as argument")
            return False
    
    if not password:
        password = os.environ.get('PATREON_PASSWORD')
        if not password:
            print("Error: Please set PATREON_PASSWORD environment variable or pass password as argument")
            return False
    
    async with async_playwright() as p:
        print("Launching browser in headless mode...")
        browser = await p.chromium.launch(
            headless=True,
            args=['--disable-blink-features=AutomationControlled']
        )
        
        context = await browser.new_context(
            viewport={'width': 1920, 'height': 1080},
            user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        
        page = await context.new_page()
        
        try:
            print("Navigating to Patreon login page...")
            await page.goto("https://www.patreon.com/login", wait_until='networkidle')
            
            print("Waiting for login form...")
            await page.wait_for_selector('input[name="email"]', timeout=10000)
            
            print(f"Filling in email: {email}")
            await page.fill('input[name="email"]', email)
            
            print("Filling in password...")
            await page.fill('input[name="password"]', password)
            
            print("Clicking login button...")
            await page.click('button[type="submit"]')
            
            print("Waiting for login to complete...")
            try:
                await page.wait_for_url("https://www.patreon.com/home", timeout=30000)
                print("Login successful!")
            except:
                # Check if we're on a different page that indicates success
                current_url = page.url
                if "login" not in current_url.lower():
                    print(f"Login appears successful (redirected to: {current_url})")
                else:
                    print("Login might have failed or requires verification")
                    # Take a screenshot for debugging
                    await page.screenshot(path="patreon_login_error.png")
                    print("Screenshot saved to patreon_login_error.png")
                    return False
            
            print("Extracting cookies...")
            cookies = await context.cookies()
            
            # Convert cookies to Netscape format for yt-dlp
            with open("patreon_cookies.txt", "w") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file is generated by patreon_auto_login.py\n")
                for cookie in cookies:
                    secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                    http_only = "TRUE" if cookie.get("httpOnly", False) else "FALSE"
                    expires = str(int(cookie.get("expires", -1)))
                    if expires == "-1":
                        expires = "0"
                    domain = cookie["domain"]
                    if not domain.startswith("."):
                        domain = "." + domain
                    path = cookie.get("path", "/")
                    name = cookie["name"]
                    value = cookie["value"]
                    
                    f.write(f"{domain}\t{http_only}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
            
            print("Cookies saved to patreon_cookies.txt")
            
            # Also save as JSON for backup
            with open("patreon_cookies.json", "w") as f:
                json.dump(cookies, f, indent=2)
            print("Cookies also saved to patreon_cookies.json (backup)")
            
            return True
            
        except Exception as e:
            print(f"Error during login: {e}")
            await page.screenshot(path="patreon_login_error.png")
            print("Screenshot saved to patreon_login_error.png")
            return False
        finally:
            await browser.close()

async def main():
    email = sys.argv[1] if len(sys.argv) > 1 else None
    password = sys.argv[2] if len(sys.argv) > 2 else None
    
    success = await login_to_patreon(email, password)
    if success:
        print("\nLogin complete! You can now use yt-dlp with --cookies patreon_cookies.txt")
        print("\nExample commands:")
        print('yt-dlp --cookies patreon_cookies.txt "https://www.patreon.com/posts/137239514"')
        print('yt-dlp --cookies patreon_cookies.txt "https://www.patreon.com/posts/secret-training-136705940"')
    else:
        print("\nLogin failed. Please check your credentials and try again.")
        sys.exit(1)

if __name__ == "__main__":
    asyncio.run(main())